# .gitlab-ci.yml

# Use the official ROS Noetic Docker image
image: ros:noetic

# Define stages for the CI pipeline
stages:
  - build

# Define jobs for each stage
build:
  stage: build
  script:
    - apt-get update && apt-get install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential
    - cd catkin_ws/src/fs-213804_tier4
    - rosdep install --from-paths . --ignore-src -r -y
    - cd ../../
    - catkin_make
